name: Git Compass

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: [portfolio-git-compass]

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - name: Install Required Modules
        run: |
          bun install

      - name: Build the Project
        run: |
          bun run build

      - name: Restart App
        run: |
          pm2 stop "Git Compass"
          pm2 reset "Git Compass"
          pm2 start "Git Compass"

    #PM2 START COMMAND: pm2 start bun --name "Git Compass" -- run start
